# Generated by Django 4.2.28 on 2026-02-07 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(max_length=50)),
                ('tone', models.CharField(max_length=50)),
                ('system_prompt', models.TextField()),
                ('llm_provider', models.CharField(choices=[('openrouter', 'OpenRouter'), ('gemini', 'Gemini'), ('deepseek', 'DeepSeek')], default='openrouter', max_length=20)),
                ('llm_model', models.CharField(default='openai/gpt-4o-mini', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='message',
            name='phase',
            field=models.CharField(blank=True, choices=[('framing', 'Framing'), ('evidence', 'Evidence'), ('counterpoint', 'Counterpoint'), ('plan', 'Plan'), ('synthesis', 'Synthesis')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='consensus',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='session',
            name='topic',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='session',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ReasoningEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=20)),
                ('rationale', models.TextField()),
                ('objections', models.JSONField(default=list)),
                ('evidence', models.JSONField(default=list)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reasoning_entries', to='debate.agent')),
                ('message', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reasoning', to='debate.message')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasoning_entries', to='debate.session')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='debate.agent'),
        ),
    ]
